config/routes.rb
Rails.application.routes.draw do
  # get 'admin/index'
  # get 'sessions/new'
  # get 'sessions/create'
  # get 'sessions/destroy'
  get 'admin' => 'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  root 'store#index' ,as: 'store_index'
  resources :products
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Depot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>


  <body>
  <div id="banner">
    <span class="title"><%= @page_title %></span>
  </div>
  <div id="columns">
    <div id="side">
      <div id="cart">
        <% if @cart %>
          <%= render @cart %>
        <% end %>
      </div>
      <ul>
        <li><a href="#">Home</a></li>
        <li><a href="#">Questions</a></li>
        <li><a href="#">News</a></li>
        <li><a href="#">Contact</a></li>
      </ul>

      <% if session[:user_id] %>
        <ul>
          <li><%= link_to 'Orders', orders_path %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users', users_path %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete %>
      <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </body>
</html>